module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'module:react-native-dotenv',
      {
        envName: 'APP_ENV',
        moduleName: '@env',
        path: '.env',
        whitelist: [
          'API_BASE',
          'RECENTLY_ADDED_MOBILES',
          'RECENTLY_ADDED_WATCHES',
          'RECENTLY_ADDED_TABLETS',
          'SEARCH',
          'DESCRIPTION',
          'LOGIN',
          'REGISTER',
          'NEW_USED_PHONES',
          'GET_PROFILE_DATA',
          'SUBMIT_OTP',
          'LOGOUT',
          'FORGOT_PASSWORD',
          'VERIFY_OTP',
          'POST_AN_AD',
          'BRANDS',
          'MODELS',
          'WISHLIST',
          'WISHLIST_GET',
          'VIDEOS',
          'HOME_SLIDER_IMAGES',
          'BLOGS',
          'FILTER',
          'MY_ADS',
          'CATEGORY',
          'ADD_WISHLIST',
          'REMOVE_WISHLIST',
          'FETCH_MESSAGES',
          'SEND_MESSAGES',
          'CONTACTS',
          'BRANDS_NO_AUTH',
          'SOCIAL_LOGIN',
        ],
      },
    ],
  ],
};
