export const Ram = [
  {key: 1, value: '1 GB'},
  {key: 2, value: '2 GB'},
  {key: 3, value: '4 GB'},
  {key: 4, value: '6 GB'},
  {key: 5, value: '8 GB'},
  {key: 6, value: '12 GB'},
  {key: 7, value: '16 GB'},
];
export const Storage = [
  {key: 1, value: '4 GB'},
  {key: 2, value: '8 GB'},
  {key: 3, value: '16 GB'},
  {key: 4, value: '32 GB'},
  {key: 5, value: '64 GB'},
  {key: 6, value: '32 GB'},
  {key: 7, value: '64 GB'},
  {key: 8, value: '128 GB'},
  {key: 9, value: '256 GB'},
  {key: 10, value: '512 GB'},
  {key: 11, value: '1 TB'},
];
export const Warranty = [
  {key: 1, value: 'No Warranty'},
  {key: 2, value: '1 month'},
  {key: 3, value: '2 months'},
  {key: 4, value: '3 months'},
  {key: 5, value: '4 months'},
  {key: 6, value: '5 months'},
  {key: 7, value: '6 months'},
  {key: 8, value: '7 months'},
  {key: 9, value: '8 months'},
  {key: 10, value: '9 months'},
  {key: 11, value: '10 months'},
  {key: 12, value: '11 months'},
  {key: 13, value: '12 months'},
];
export const Pta_status = [
  {key: 1, value: 'Approved'},
  {key: 2, value: 'Not Approved'},
];
export const Condition = [
  {key: 1, value: 'New'},
  {key: 2, value: 'Used'},
  {key: 3, value: 'Refurbished'},
];

// export const City = [
//   {key: 1, value: 'Karachi'},
//   {key: 2, value: 'Lahore'},
//   {key: 3, value: 'Faisalabad'},
// ];
export const City = [
  {label: 'Karachi', value: 'Karachi'},
  {label: 'Lahore', value: 'Lahore'},
  {label: 'Islamabad', value: 'Islamabad'},
  {label: 'Faisalabad', value: 'Faisalabad'},
  {label: 'Rawalpindi', value: 'Rawalpindi'},
  {label: 'Multan', value: 'Multan'},
  {label: 'Gujranwala', value: 'Gujranwala'},
  {label: 'Peshawar', value: 'Peshawar'},
  {label: 'Quetta', value: 'Quetta'},
  {label: 'Sialkot', value: 'Sialkot'},
  {label: 'Gujrat', value: 'Gujrat'},
  {label: 'Bahawalpur', value: 'Bahawalpur'},
  {label: 'Sargodha', value: 'Sargodha'},
  {label: 'Sukkur', value: 'Sukkur'},
  {label: 'Jhang', value: 'Jhang'},
  {label: 'Larkana', value: 'Larkana'},
  {label: 'Sheikhupura', value: 'Sheikhupura'},
  {label: 'Rahim Yar Khan', value: 'Rahim Yar Khan'},
  {label: 'Chiniot', value: 'Chiniot'},
  {label: 'Sahiwal', value: 'Sahiwal'},
  {label: 'Mardan', value: 'Mardan'},
  {label: 'Kasur', value: 'Kasur'},
  {label: 'Dera Ghazi Khan', value: 'Dera Ghazi Khan'},
  {label: 'Nawabshah', value: 'Nawabshah'},
  {label: 'Mingora', value: 'Mingora'},
  {label: 'Okara', value: 'Okara'},
  {label: 'Mirpur Khas', value: 'Mirpur Khas'},
  {label: 'Chiniot', value: 'Chiniot'},
  {label: 'Kamoke', value: 'Kamoke'},
  {label: 'Sadiqabad', value: 'Sadiqabad'},
  {label: 'Burewala', value: 'Burewala'},
  {label: 'Jhelum', value: 'Jhelum'},
  {label: 'Kohat', value: 'Kohat'},
  {label: 'Khanewal', value: 'Khanewal'},
  {label: 'Dera Ismail Khan', value: 'Dera Ismail Khan'},
  {label: 'Gojra', value: 'Gojra'},
  {label: 'Bahawalnagar', value: 'Bahawalnagar'},
  {label: 'Muridke', value: 'Muridke'},
  {label: 'Pakpattan', value: 'Pakpattan'},
  {label: 'Abottabad', value: 'Abottabad'},
  {label: 'Tando Adam', value: 'Tando Adam'},
  {label: 'Jaranwala', value: 'Jaranwala'},
  {label: 'Khairpur', value: 'Khairpur'},
  {label: 'Chishtian', value: 'Chishtian'},
  {label: 'Daska', value: 'Daska'},
  {label: 'Mandi Bahauddin', value: 'Mandi Bahauddin'},
  {label: 'Ahmedpur East', value: 'Ahmedpur East'},
  {label: 'Kamalia', value: 'Kamalia'},
  {label: 'Tando Allahyar', value: 'Tando Allahyar'},
  {label: 'Khuzdar', value: 'Khuzdar'},
  {label: 'Vihari', value: 'Vihari'},
  {label: 'Attock', value: 'Attock'},
  {label: 'Badin', value: 'Badin'},
  {label: 'Sanghar', value: 'Sanghar'},
  {label: 'Nankana Sahib', value: 'Nankana Sahib'},
  {label: 'Hafizabad', value: 'Hafizabad'},
  {label: 'Kotli', value: 'Kotli'},
  {label: 'Lodhran', value: 'Lodhran'},
  {label: 'Nowshera', value: 'Nowshera'},
  {label: 'Charsadda', value: 'Charsadda'},
  {label: 'Jamshoro', value: 'Jamshoro'},
  {label: 'Kandhkot', value: 'Kandhkot'},
  {label: 'Mianwali', value: 'Mianwali'},
  {label: 'Hassan Abdal', value: 'Hassan Abdal'},
  {label: 'Muzaffargarh', value: 'Muzaffargarh'},
  {label: 'Toba Tek Singh', value: 'Toba Tek Singh'},
  {label: 'Jhang Sadr', value: 'Jhang Sadr'},
  {label: 'Khairpur Mir’s', value: 'Khairpur Mir’s'},
  {label: 'Narowal', value: 'Narowal'},
  {label: 'Shakargarh', value: 'Shakargarh'},
  {label: 'Hujra', value: 'Hujra'},
  {label: 'Kabirwala', value: 'Kabirwala'},
  {label: 'Kasur', value: 'Kasur'},
  {label: 'Mansehra', value: 'Mansehra'},
  {label: 'Layyah', value: 'Layyah'},
  {label: 'Kambar', value: 'Kambar'},
  {label: 'Moro', value: 'Moro'},
  {label: 'Mianwali', value: 'Mianwali'},
  {label: 'Turbat', value: 'Turbat'},
  {label: 'Shahdadkot', value: 'Shahdadkot'},
  {label: 'Nawabshah', value: 'Nawabshah'},
  {label: 'Dadu', value: 'Dadu'},
  {label: 'Ali Pur', value: 'Ali Pur'},
  {label: 'Lodhran', value: 'Lodhran'},
  {label: 'Kotli', value: 'Kotli'},
  {label: 'Loralai', value: 'Loralai'},
  {label: 'Dera Allahyar', value: 'Dera Allahyar'},
  {label: 'Pakpattan', value: 'Pakpattan'},
  {label: 'Sehwan', value: 'Sehwan'},
  {label: 'Chaman', value: 'Chaman'},
  {label: 'Tando Jam', value: 'Tando Jam'},
  {label: 'Kandiaro', value: 'Kandiaro'},
  {label: 'Kunjah', value: 'Kunjah'},
  {label: 'Sahiwal', value: 'Sahiwal'},
  {label: 'Kamber', value: 'Kamber'},
  {label: 'Malakand', value: 'Malakand'},
  {label: 'Mithi', value: 'Mithi'},
  {label: 'Ziarat', value: 'Ziarat'},
  {label: 'Loralai', value: 'Loralai'},
  {label: 'Dera Murad Jamali', value: 'Dera Murad Jamali'},
  {label: 'Kohlu', value: 'Kohlu'},
  {label: 'Gwadar', value: 'Gwadar'},
  {label: 'Dera Bugti', value: 'Dera Bugti'},
  {label: 'Tando Allahyar', value: 'Tando Allahyar'},
  {label: 'Kot Addu', value: 'Kot Addu'},
  {label: 'Turbat', value: 'Turbat'},
  {label: 'Dullewala', value: 'Dullewala'},
  {label: 'Shahkot', value: 'Shahkot'},
  {label: 'Harunabad', value: 'Harunabad'},
  {label: 'Pattoki', value: 'Pattoki'},
  {label: 'Mamu Kanjan', value: 'Mamu Kanjan'},
  {label: 'Jalalpur', value: 'Jalalpur'},
  {label: 'Bhai Pheru', value: 'Bhai Pheru'},
  {label: 'Kabirwala', value: 'Kabirwala'},
  {label: 'Kot Radha Kishan', value: 'Kot Radha Kishan'},
  {label: 'Hujra', value: 'Hujra'},
  {label: 'Pindi Bhattian', value: 'Pindi Bhattian'},
  {label: 'Khalabat', value: 'Khalabat'},
  {label: 'Narang', value: 'Narang'},
  {label: 'Topi', value: 'Topi'},
  {label: 'Kamra', value: 'Kamra'},
  {label: 'Mitha Tiwana', value: 'Mitha Tiwana'},
  {label: 'Basirpur', value: 'Basirpur'},
  {label: 'Naushahro Feroze', value: 'Naushahro Feroze'},
  {label: 'Tando Muhammad Khan', value: 'Tando Muhammad Khan'},
  {label: 'Haripur', value: 'Haripur'},
  {label: 'Shikarpur', value: 'Shikarpur'},
  {label: 'Bhakkar', value: 'Bhakkar'},
  {label: 'Kharian', value: 'Kharian'},
  {label: 'Lala Musa', value: 'Lala Musa'},
  {label: 'Kasur', value: 'Kasur'},
  {label: 'Mian Channun', value: 'Mian Channun'},
  {label: 'Kundian', value: 'Kundian'},
  {label: 'Bhawana', value: 'Bhawana'},
  {label: 'Dajal', value: 'Dajal'},
  {label: 'Chawinda', value: 'Chawinda'},
  {label: 'Qadirpur Ran', value: 'Qadirpur Ran'},
  {label: 'Tandlianwala', value: 'Tandlianwala'},
  {label: 'Khewra', value: 'Khewra'},
  {label: 'Kahror Pakka', value: 'Kahror Pakka'},
  {label: 'Toba Tek Singh', value: 'Toba Tek Singh'},
  {label: 'Tando Qaiser', value: 'Tando Qaiser'},
  {label: 'Khairpur Nathan Shah', value: 'Khairpur Nathan Shah'},
  {label: 'Gujar Khan', value: 'Gujar Khan'},
  {label: 'Haripur', value: 'Haripur'},
  {label: 'Ghotki', value: 'Ghotki'},
  {label: 'Sarai Alamgir', value: 'Sarai Alamgir'},
  {label: 'Pir Mahal', value: 'Pir Mahal'},
  {label: 'Dinga', value: 'Dinga'},
  {label: 'Jampur', value: 'Jampur'},
  {label: 'Mangla', value: 'Mangla'},
  {label: 'Qadirpur Ran', value: 'Qadirpur Ran'},
  {label: 'Pishin', value: 'Pishin'},
  {label: 'Kahna', value: 'Kahna'},
  {label: 'Mianwali', value: 'Mianwali'},
  {label: 'Samundri', value: 'Samundri'},
  {label: 'Renala Khurd', value: 'Renala Khurd'},
  {label: 'Kahuta', value: 'Kahuta'},
  {label: 'Mehar', value: 'Mehar'},
  {label: 'Narowal', value: 'Narowal'},
  {label: 'Khushab', value: 'Khushab'},
  {label: 'Gandava', value: 'Gandava'},
  {label: 'Khairpur', value: 'Khairpur'},
  {label: 'Shahdadpur', value: 'Shahdadpur'},
  {label: 'Matiari', value: 'Matiari'},
  {label: 'Sibi', value: 'Sibi'},
  {label: 'Muzaffarabad', value: 'Muzaffarabad'},
  {label: 'Chaman', value: 'Chaman'},
  {label: 'Miran Shah', value: 'Miran Shah'},
  {label: 'Uthal', value: 'Uthal'},
  {label: 'Moro', value: 'Moro'},
  {label: 'Tump', value: 'Tump'},
  {label: 'Shahpur', value: 'Shahpur'},
  {label: 'Sakrand', value: 'Sakrand'},
  {label: 'Sehwan Sharif', value: 'Sehwan Sharif'},
  {label: 'Khairpur Tamewali', value: 'Khairpur Tamewali'},
  {label: 'Topi', value: 'Topi'},
  {label: 'Leiah', value: 'Leiah'},
  {label: 'Mingora', value: 'Mingora'},
  {label: 'Ghakhar Mandi', value: 'Ghakhar Mandi'},
  {label: 'Tando Ghulam Ali', value: 'Tando Ghulam Ali'},
  {label: 'Thatta', value: 'Thatta'},
  {label: 'Kandhkot', value: 'Kandhkot'},
  {label: 'Hattar', value: 'Hattar'},
  {label: 'Arifwala', value: 'Arifwala'},
  {label: 'Bannu', value: 'Bannu'},
  {label: 'Parachinar', value: 'Parachinar'},
  {label: 'Gakuch', value: 'Gakuch'},
  {label: 'Hangu', value: 'Hangu'},
  {label: 'Timargara', value: 'Timargara'},
  {label: 'Gwadar', value: 'Gwadar'},
  {label: 'Kalat', value: 'Kalat'},
  {label: 'Gandawa', value: 'Gandawa'},
  {label: 'Rakhni', value: 'Rakhni'},
  {label: 'Loralai', value: 'Loralai'},
  {label: 'Gaddani', value: 'Gaddani'},
  {label: 'Kulachi', value: 'Kulachi'},
  {label: 'Zaida', value: 'Zaida'},
  {label: 'Jand', value: 'Jand'},
  {label: 'Lachi', value: 'Lachi'},
  {label: 'Havelian', value: 'Havelian'},
  {label: 'Ladhewala Waraich', value: 'Ladhewala Waraich'},
  {label: 'Kamoke', value: 'Kamoke'},
  {label: 'Matiari', value: 'Matiari'},
  {label: 'Nankana Sahib', value: 'Nankana Sahib'},
  {label: 'Kundian', value: 'Kundian'},
  {label: 'Renala Khurd', value: 'Renala Khurd'},
  {label: 'Risalpur', value: 'Risalpur'},
  {label: 'Kot Mumin', value: 'Kot Mumin'},
  {label: 'Kamra', value: 'Kamra'},
  {label: 'Pindi Bhattian', value: 'Pindi Bhattian'},
  {label: 'Ghakhar Mandi', value: 'Ghakhar Mandi'},
  {label: 'Gojra', value: 'Gojra'},
  {label: 'Makhdumpur', value: 'Makhdumpur'},
  {label: 'Khurrianwala', value: 'Khurrianwala'},
  {label: 'Gurjaani', value: 'Gurjaani'},
];

export const CategoryList = [
  {key: 1, value: 'Mobile'},
  {key: 1, value: 'Tablet'},
  {key: 1, value: 'Watch'},
];
